// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybowdicitmmrltuyvxcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlib3dkaWNpdG1tcmx0dXl2eGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MjQ3ODUsImV4cCI6MjA2ODMwMDc4NX0.EyArJ3ROfij_B3l1JcsOiHFyMfh_z8SzbmwWPqGod7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});